name: cloud_music
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  # 轮播控件
  flutter_swiper: ^1.1.6
  # dio是一个强大的Dart Http请求库
  dio: ^3.0.10
  event_bus: ^1.1.1
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  cached_network_image: ^2.4.1
  fluttertoast: ^7.1.6
  flutter_webview_plugin: ^0.3.11
  #  一组加载指示器
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+2
  pull_to_refresh: ^1.6.3
  provider: ^4.3.2+3
  flutter_screenutil: ^4.0.0
  date_format: ^1.0.9
  common_utils: ^1.2.1
  # lutter 播放器 chewie
  chewie: ^0.12.0
  video_player: ^1.0.1
  marquee_text: ^1.1.0
  dio_cookie_manager: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

    - images/location.png
    - images/timing.png
    - images/alarm.png
    - images/ticket.png
    - images/shopping_cart.png
    - images/coupon.png
    - images/game.png
    - images/broadcast.png
    - images/music_free_flow.png
    - images/drawer_message.png
    - images/drawer_friend.png
    - images/drawer_skin.png
    - images/drawer_music.png
    - images/pocket_ringtone.png
    - images/night_mode.png
    - images/day_mode.png
    - images/setting.png
    - images/app_shut_down.png
    - images/about.png
    - images/help.png
    - images/cloud_center.png


    # 我的页面图片资源
    - images/my/shortcut_fm.png
    - images/my/download_manager.png

    # 发现页面图片资源

    - images/find/t_dragonball_icn_daily.png
    - images/find/t_dragonball_icn_look.png
    - images/find/t_dragonball_icn_playlist.png
    - images/find/t_dragonball_icn_radio.png
    - images/find/t_dragonball_icn_rank.png
    - images/find/bg_song_list.9.png
    - images/t_dragonball_icn_rank.png
    - images/t_dragonball_icn_digitalalbum.png

    # 登入页
    - images/wx.png
    - images/qq.png
    - images/weibo.png
    - images/wangyi.png
    - images/icon_checkbox.png
    - images/icon_right.png
    - images/login_page_logo.png

    # 歌单详情
    - images/album/album_comment.png
    - images/album/album_share.png
    - images/album/album_download.png
    - images/album/album_multiple_selection.png
    - images/album/track_mv.png
    - images/album/track_more.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
